### PR TITLE
Updated to use the assets repo NHS-R Community Logo and removed png file

### PR DESCRIPTION
**Pull request by Lextuga007**

### CODE REVIEW

**Review by tomjemmett — CHANGES_REQUESTED** [review]
(Looking on mobile) I'm not sure the links look correct here, we have an <a> tag inside of a markdown link [] - I think we just need to drop the markdown link

**Comment by Lextuga007** [comment]
I think I was following the previous code but got it muddled. Strangely looks ok on my phone when I tried it but best to remove the [] as you suggest - thanks!

**Comment by Lextuga007** [comment]
I've made the changes - is there a way on GitHub to say that or is it best to comment, like this? Thanks

**Review by tomjemmett — APPROVED** [review]
approving for merge, slight pedantry, but should be consistent with use of " or ' in html attributes (my vote would be to always use ")

**Pull request merged**
